#!/usr/bin/env sh
# Generate /etc/nxagentd.conf from the add-on options, then run the agent
# in the foreground so its log goes to the Home Assistant add-on log.
set -e

OPTIONS=/data/options.json
CONF=/etc/nxagentd.conf

MASTER="$(jq -r '.master_servers // empty' "$OPTIONS")"
NODE_HOSTNAME="$(jq -r '.hostname // empty' "$OPTIONS")"

{
    echo "# Generated by the Home Assistant NetXMS Agent add-on. Do not edit by hand."
    echo "LogFile = {stdout}"
    # Persist agent state in the add-on's /data volume (Home Assistant standard).
    echo "DataDirectory = /data"

    if [ -n "$MASTER" ]; then
        echo "MasterServers = ${MASTER}"
    fi

    if [ -n "$NODE_HOSTNAME" ]; then
        echo "Hostname = ${NODE_HOSTNAME}"
    fi

    # Any extra raw nxagentd.conf lines pasted by the user (DebugLevel, etc.).
    jq -r '.extra_config[]?' "$OPTIONS"
} > "$CONF"

echo "----- effective /etc/nxagentd.conf -----"
cat "$CONF"
echo "----------------------------------------"

exec nxagentd -f -c "$CONF"
